var data = [
  { inch: "6.5", name: "Big Android Phone ", img: "images/1.jpg", category: "android", text: "short description" },
  { inch: "4.5", name: "Small Android Phone", img: "images/21.jpg", category: "android", text: "short description" },
  { inch: "4.5", name: "Small Iphone", img: "images/10.jpg", category: "ios", text: "short description" },
  { inch: "4.2", name: "Small Android Phone 2", img: "images/2.jpg", category: "android", text: "short description" },
  { inch: "5", name: "Middle Asus Phone", img: "images/3.jpg", category: "android", text: "short description" },
  { inch: "5.2", name: "Not Small Android", img: "images/9.jpg", category: "android", text: "short description" },
  { inch: "5.5", name: "Android phone", img: "images/11.jpg", category: "android", text: "short description" },
  { inch: "5", name: "Android phone 2 ", img: "images/7.jpg", category: "android", text: "short description" },
  { inch: "6", name: "Iphone", img: "images/6.jpg", category: "ios", text: "short description" },
  { inch: "5.2", name: "Android Phone 3 ", img: "images/12.jpg", category: "android", text: "short description" },
  { inch: "5.7", name: "Android Phone 4 ", img: "images/4.jpg", category: "android", text: "short description" },
  { inch: "5.5", name: "Android Phone 5 ", img: "images/13.jpg", category: "android", text: "short description" },
  { inch: "5.7", name: "Iphone 2", img: "images/14.jpg", category: "ios", text: "short description" },
  { inch: "4.5", name: "Iphone 3 ", img: "images/8.jpg", category: "ios", text: "short description" },
  { inch: "5.2", name: "Iphone 4 ", img: "images/15.jpg", category: "ios", text: "short description" },
  { inch: "5.7", name: " Iphone 5 ", img: "images/17.jpg", category: "ios", text: "short description" },
  { inch: "4.5", name: "Iphone 6 ", img: "images/19.jpg", category: "ios", text: "short description" },
  { inch: "5.5", name: "Iphone 7 ", img: "images/20.jpg", category: "ios", text: "short description" },
  { inch: "4.9", name: "Iphone 8", img: "images/5.jpg", category: "ios", text: "short description" },
  { inch: "6.3", name: "Large Android ", img: "images/22.jpg", category: "android", text: "short description" },
  /*  { inch: "5.5", name: "Black Iphone ", img: "images/23.jpg", category: "ios", text: "short description" },
    { inch: "5.5", name: "Old Grey Android", img: "images/24.jpg", category: "android", text: "short description" },
    { inch: "5.7", name: "Grey Phone", img: "images/25.jpg", category: "android", text: "short description" },
    { inch: "5.5", name: "Dark White Phone ", img: "images/26.jpg", category: "android", text: "short description" },
    { inch: "4.5", name: "Black Iphone 9", img: "images/27.jpg", category: "ios", text: "short description" },
    { inch: "4.5", name: "Mini Iphone ", img: "images/29.jpg", category: "ios", text: "short description" },
    { inch: "5", name: "Mini Android", img: "images/30.jpg", category: "android", text: "short description" },
    { inch: "5.2", name: " Black Phone", img: "images/31.jpg", category: "ios", text: "short description" },
    { inch: "5.5", name: "Big Black Phone ", img: "images/32.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/33.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/34.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/36.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/37.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/43.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/44.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/45.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/46.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/47.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/48.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/49.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/50.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/52.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/53.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/54.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/55.jpg", category: "", text: "short description" },
    { inch: "", name: "w ", img: "images/56.jpg", category: "", text: "short description" } */
];

